name: ci

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Setup Environment
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      - name: Log variables
        run: |
          echo $GITHUB_REF
          echo ${{ steps.extract_branch.outputs.branch }}
          echo ${{ steps.tag.outputs.result }}
