name: ci

on:
  create:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Setup Environment
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.x.x

      - name: Log versions
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
